In [1]:
import pandas as pd
df = pd.read_csv(r"D:\innomatics_247B\python\anakonda\python_427B\zepto_DA\zepto_fruits.csv")
df

,Name,Original Price,Discounted Price,Discount Percent,Price (raw),Premium,quantity,Rating,Review Count,Delivery Time,Category,Price
0,Banana Robusta,31,11,64.52,₹20 | ₹31 | ₹11,No,NaN,NaN,31,7 mins,fruits,31
1,Guava (Thai),64,21,67.19,₹43 | ₹64 | ₹21,No,500 g,NaN,500,7 mins,fruits,64
2,Baby Apple Shimla,139,30,78.42,₹109 | ₹139 | ₹30,No,500 g,NaN,500,7 mins,fruits,139
3,Indian Red Dragon Fruit,101,37,63.37,₹64 | ₹101 | ₹37,No,NaN,NaN,101,7 mins,fruits,101
4,Pineapple Slice,86,20,76.74,₹66 | ₹86 | ₹20,No,175 g,NaN,175,7 mins,fruits,86
...,...,...,...,...,...,...,...,...,...,...,...,...
136,Organic Bitter Gourd,54,12,77.78,₹42 | ₹54 | ₹12,No,250 g,NaN,250,7 mins,fruits,54
137,Super Sweetcorn Kernels,240,54,77.50,₹186 | ₹240 | ₹54,No,500 g,NaN,500,7 mins,fruits,240
138,Mango Totapuri Combo,306,104,66.01,₹202 | ₹306 | ₹104,No,Mango Totapuri Combo,NaN,306,7 mins,fruits,306
139,"Daily Good Cashew ( W320)(200gms), Daily Good ...",740,220,70.27,₹520 | ₹740 | ₹220,No,"Daily Good Cashew ( W320)(200gms), Daily Good ...",4.4,497,7 mins,fruits,740
140,"Daily Good Cashew / Kaju Split(100gms), Daily ...",915,258,71.80,₹657 | ₹915 | ₹258,No,"Daily Good Cashew / Kaju Split(100gms), Daily ...",4.7,598,7 mins,fruits,915

In [2]:
df.drop(['Price (raw)','Price'], axis=1, inplace=True)

In [3]:
df['Name'] = df['Name'].astype(str).str.replace(r'[/\-&(|].*', '', regex=True).str.strip()

In [4]:
import re
def extract_quantity(qty):
    qty = str(qty).strip()

    # ✅ Extract only: 50 g, 200 ml, 1 kg, 500 ltr, etc.
    match = re.search(r'\b(\d+)\s*(g|kg|ml|l|ltr|pcs)\b', qty, re.IGNORECASE)
    if match:
        return match.group(1) + " " + match.group(2).lower()

    # ❌ If no number + unit is found, return None or keep original
    return None  # or return qty if you want to keep the text

# Apply to DataFrame column
df['quantity'] = df['quantity'].apply(extract_quantity)

In [5]:
df

,Name,Original Price,Discounted Price,Discount Percent,Premium,quantity,Rating,Review Count,Delivery Time,Category
0,Banana Robusta,31,11,64.52,No,None,NaN,31,7 mins,fruits
1,Guava,64,21,67.19,No,500 g,NaN,500,7 mins,fruits
2,Baby Apple Shimla,139,30,78.42,No,500 g,NaN,500,7 mins,fruits
3,Indian Red Dragon Fruit,101,37,63.37,No,None,NaN,101,7 mins,fruits
4,Pineapple Slice,86,20,76.74,No,175 g,NaN,175,7 mins,fruits
...,...,...,...,...,...,...,...,...,...,...
136,Organic Bitter Gourd,54,12,77.78,No,250 g,NaN,250,7 mins,fruits
137,Super Sweetcorn Kernels,240,54,77.50,No,500 g,NaN,500,7 mins,fruits
138,Mango Totapuri Combo,306,104,66.01,No,None,NaN,306,7 mins,fruits
139,Daily Good Cashew,740,220,70.27,No,None,4.4,497,7 mins,fruits
140,Daily Good Cashew,915,258,71.80,No,None,4.7,598,7 mins,fruits

In [7]:
#df.to_csv('zepto_product_name.csv', index=False, encoding='utf-8')